---
# tasks file for apache
-   name: Ensure that the httpd package is not install on the system
    yum:
       name: httpd
       state: absent
-   name: Ensure that the httpd-tools package is not install on the system
    yum:
        name: httpd-tools
        state: absent
